baseURL: "https://calamarcroustillant.github.io/"
theme: "hydrogen"

title: "Fawwaaz Koodruth"
author: "Fawwaaz Kootdruth"
# copyright: "Copyright © 2024 All Rights Reserved."

paginate: 3
languageCode: "en"

defaultContentLanguage:  "en"
enableInlineShortcodes: true

# params:
#   copyright: "Copyright"

menu:
  main:
    - identifier: "github"
      name: "Github"
      url: "https://github.com/calamarcroustillant"
      weight: 10
      
    - identifier: "about"
      name: "About"
      url: "/about"
      weight: 5

    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1

taxonomies:
  category: "categories"
  tag: "tags"
  series: "series"

enableEmoji: true

markup:
  goldmark:
    renderer:
      unsafe: true